#!/bin/bash

# A WIP. To be made better in the future.

cmd="\grep -A 1 description ""$HOME""/.config/sxhkd/sxhkdrc | sed -e s/--/\ /g"
case $1 in
	d) cmd="$cmd -e s/description:\ //g" && echo -e "$(eval "$cmd")" | rofi -dmenu -p "sxhkd keybindings";; # If "d" arg is passed, show descriptions without "description: ".
	e) $EDITOR "$HOME"/.config/sxhkd/sxhkdrc;; # If "e" arg is passed, edit config with $EDITOR.
	*) echo -e "$(eval "$cmd")" | rofi -dmenu -p "sxhkd keybindings";; # If anything (or nothing) is passed, display keybindings like normal.
esac
